{"name": "test_case", "status": "failed", "statusDetails": {"message": "AssertionError: Not found", "trace": "self = <tests.pages.test.test testMethod=test_case>, args = (), kwargs = {}\n\n    def wraps(self, *args, **kwargs):\n>       self.assertRaises(exception, fn, self, *args, **kwargs)\n\ncore\\decorators\\expect.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @allure.feature('Feature1')\n    @allure.story('Story1')\n    @expect_exception(AttributeError)\n    def test_case(self):\n        print(\"test case\")\n>       raise AssertionError(\"Not found\")\nE       AssertionError: Not found\n\ntests\\pages\\test.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "2a0d2a2a-ac6f-476d-9cbc-162a2c2cae0f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1d5b0143-48b0-4522-a99d-d963e0246dea-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cffeedda-8f8b-413b-8d4a-8cce87a92dcf-attachment.txt", "type": "text/plain"}], "start": 1549967001699, "stop": 1549967001699, "uuid": "d7f432cf-2084-45f1-b6a5-9d9a37369bf3", "historyId": "c74189de3a946ee996227053c0d78a15", "fullName": "tests.pages.test.test#test_case", "labels": [{"name": "story", "value": "Story1"}, {"name": "feature", "value": "Feature1"}, {"name": "parentSuite", "value": "tests.pages"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "test"}, {"name": "host", "value": "XIPL0515"}, {"name": "thread", "value": "16832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pages.test"}]}